# Blades
trislash = "Trislash"
strider = "Strider"
ghost_fluerette = "Ghost Fluerette"
whirlpool = "Whirlpool"
yo_yo = "Yo-Yo"
tack_rush = "Tack Rush"  # Unused
altrise = "Altrise"
headhunt = "Head Hunt"
smash = "Smash"
eintraf = "Eintraf"
zweitraf = "Zweitraf"
dreitraf = "Dreitraf"
trafia = "Trafia"  # Unused
whipper = "Whipper"
nettle = "Nettle"
spike = "Spike"
clarity = "Clarity"
southern_cross = "Southern Cross"
murakumo = "Murakumo"
muramasa = "Muramasa"

# Assaults
step_arrow = "Step Arrow"
aura_assault = "Aura Assault"
junk_ball = "Junk Ball"
pressure = "Pressure"
sharpness = "Sharpness"
kamikaze = "Kamikaze"
silpheed = "Silpheed"
biting = "Biting"
vjorum = "Vjorum"

# Shots
throw_dagger = "Throw Dagger"
twin_shot = "Twin Shot"
stamp = "Stamp"
cold_spear = "Cold Spear"
starfall = "Starfall"
blue_wisp = "Blue Wisp"
red_wisp = "Red Wisp"
green_wisp = "Green Wisp"
bounder = "Bounder"
plasma_rifle = "Plasma Rifle"
shell_flow = "Shell Flow"
antimaterial = "Anti-Material"
bunker_buster = "Bunker Buster"
slug_laser = "Slug Laser"
mirror_wall = "Mirror Wall"
pulse = "Pulse"
tornado = "Tornado"
seven_way = "7 Way"
grand_blaze = "Grand Blaze"

# Charges
lock_shot = "Lock Shot"
lightning = "Lightning"
nova = "Nova"
force_bit = "Force Bit"  # Unused
graviton = "Graviton"  # Unused
solomon = "Solomon"
howling = "Howling"
stgb = "S.T.G.B."

# Customs
b_commander = "B-Commander"
s_commander = "S-Commander"
c_quick = "C-Quick"
s_combarta = "S-Combarta"  # Unused
auto_repair = "Auto-Repair"
free_vernier = "Free Vernier"
b_mastery = "B-Mastery"
a_mastery = "A-Mastery"
s_mastery = "S-Mastery"
c_mastery = "C-Mastery"
ep_saving = "EP Saving"
s_full_auto = "S-Full Auto"
c_full_auto = "C-Full Auto"
balancer = "Balancer"
hard_lock = "Hard Lock"
lock_circle = "Lock Circle"
floater = "Floater"
virus_transform = "Virus Transform"
applica = "A-Applica"

# Stat Ups
small_life = "Life Max Up 50"
med_life = "Life Max Up 100"
large_life = "Life Max Up 200"
small_energy = "Energy Max Up 50"
med_energy = "Energy Max Up 100"
large_energy = "Energy Max Up 200"

# Stage Unlocks
unlock_7b = "Stage 7B Unlocked"
unlock_10b = "Stage 10B Unlocked"
